### ISSUE TITLE
Security ?

### ISSUE THREAD

**Issue by mistic100** [plegall/Piwigo-check_files_integrity#1]
What if someone modifies a file and the sums file ? Assuming the plugin was already installed.

You could add a pre-check of the sums file itself against the sum provided by piwigo.org, or always rely on sums provided by piwigo.org (which does not prevent against man-in-the-middle attacks, unless forcing HTTPS on piwigo.org)

**Comment by plegall** [comment]
What if the hacker simply modifies the plugin to "return true"?

As soon as the hacker has access to filesystem, I don't see any way to make things 100% reliable :-/

I would be fine with serving the sum files from piwigo.org. But would that really be more reliable? Let's imagine this workflow:

1. Piwigo (with this plugin) generates the sha1 of data/piwigo-2.8.3-sums.txt
2. Piwigo requests something like http://piwigo.org/api/chef_files_integrity.php?version=2.8.3&sha1=...
3. piwigo.org returns true/false
4. if false, Piwigo displays an error message, if true Piwigo starts to check core files

Would that be the workflow you have in mind?

**Comment by mistic100** [comment]
Yes that was my idea but you have a good point.

Perhaps the best solution is to add a warning on the plugin page saying this is not a security audit tool.

And also advise to manually overwrite the plugin when asking someone on the forum to do the check.

**Comment by plegall** [comment]
Yes, that's close to what I said on http://piwigo.org/forum/viewtopic.php?pid=165556#p165556 (read the whole thread to understand why I quickly wrote this plugin ;-)
